---
- name: Install Jenkins and Docker
  hosts: ec2
  become: yes

  tasks:
    - name: Update APT package cache
      apt:
        update_cache: yes

    - name: Install Java Sdk
      apt:
        name: openjdk-11-jdk
        state: present
    

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Run Jenkins Docker Container
      docker_container:
        name: jenkins
        image: jenkins/jenkins:lts
        state: started
        restart_policy: always
        ports:
          - "8080:8080"
          - "50000:50000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - jenkins_home:/var/jenkins_home

    - name: Install Docker inside Jenkins container
      command: docker run -d --name try-docker -v /var/run/docker.sock:/var/run/docker.sock docker:latest

   
    - name: Install Docker on Jenkins Agent
      apt:
        name: docker.io
        state: present

    - name: Get initial admin password
      command: docker exec -it jenkins cat /var/jenkins_home/secrets/initialAdminPassword
      register: initial_admin_password

    - name: Display initial admin password
      debug:
        var: initial_admin_password.stdout

    
