---
- name: Install python3, java, jenkins
  hosts: ec2
  become: true

  tasks:
  - name: update apt package
    apt:
      update_cache: yes
      

  - name: Install Java Sdk
    apt:
      name: openjdk-11-jdk
      state: present
    become: yes

  - name : Add jenkins key
    shell : wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | sudo apt-key add -


  - name : Add jenkins repo
    become: yes
    apt_repository:
         repo: deb http://pkg.jenkins.io/debian-stable binary/

  - name: Install Jenkins
    become: yes
    apt:
      name: jenkins

  - name: Start Jenkins service
    service:
      name: jenkins
      state: started
      enabled: yes

  - name: Wait for Jenkins to start
    wait_for:
      port: 8080
      timeout: 300

  - name: Install Docker
    apt:
      name: docker.io
      state: present
    become: yes

  - name: Add user to the docker group
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes
    tags: docker
  

  - name: Create a new user and add to sudo group
    user:
      name: "{{ ansible_user }}"
      state: present
      groups: sudo
    become: yes


  
